### PR TITLE
Minor update

### PR DESCRIPTION
**Pull request by pyav**
Minor update to change em dash to dash.

### CODE REVIEW

**Comment by sashank** [comment]
Sorry i did not realize you have access to main branch and committed already.  Thanks anyway for these changes , i appreciate it !

**Comment by pyav** [comment]
The contributions file was already updated in the upstream earlier, I don't know how the same changes went from my fork. 
Thanks.

**Comment by sashank** [comment]
Because you had permissions in main repo too ! no worries , this is good .

**Comment by pyav** [comment]
Thanks.

**Pull request merged**
